-- Turn on foreign key constraints
PRAGMA foreign_keys = ON;

-- Start a transaction for safety
BEGIN TRANSACTION;

-- Delete data from tables in reverse order of dependencies
DELETE FROM PARTECIPAZIONI_EVENTI;
DELETE FROM CLASSIFICA;
DELETE FROM CAMPIONATI;
DELETE FROM EVENTI;
DELETE FROM NOTIZIE;
DELETE FROM IMMAGINI;
DELETE FROM PRENOTAZIONI;
DELETE FROM CAMPI;
DELETE FROM GIOCATORI;
DELETE FROM SQUADRE;
DELETE FROM UTENTI;
DELETE FROM TIPI_UTENTE;

-- Reset all auto-increment counters
DELETE FROM sqlite_sequence WHERE name IN (
  'TIPI_UTENTE', 'UTENTI', 'SQUADRE', 'GIOCATORI', 'CAMPI',
  'PRENOTAZIONI', 'IMMAGINI', 'NOTIZIE', 'EVENTI',
  'CAMPIONATI', 'CLASSIFICA', 'PARTECIPAZIONI_EVENTI'
);

-- Commit the transaction
COMMIT;